application: wiki9839
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /_edit/stylesheets
  static_dir: stylesheets

- url: /_history/stylesheets
  static_dir: stylesheets

- url: /.*
  script: wikimain.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
